### ISSUE TITLE
Remote debugger doesn't work for Go (Unverified breakpoint) when using delve api v2

### ISSUE THREAD

**Issue by cheptsov** [Microsoft/vscode-go#1163]
OS X Sierra 10.12.1
VS Code 1.15.1
Go extension 0.6.63

Repo: https://github.com/cheptsov/wiki

Steps to reproduce:
1. Breakpoint: `main:go:39`
2. Terminal: `make deploy`
3. Debug `Remote Docker`

Debug Console:
```Verbose logs are written to:
/var/folders/qy/mzvdq19s40l_sbj55957ptx80000gn/T/vscode-go-debug.txt
2:40:59 PM, 8/24/2017
InitializeRequest
InitializeResponse
InitializeEvent
SetBreakPointsRequest
All cleared
Creating on: /Users/andreycheptsov/work/src/github.com/cheptsov/wiki/main.go (/app/main.go) :39
Error on CreateBreakpoint
All set:[null]
SetBreakPointsResponse
ConfigurationDoneRequest
ContinueRequest
ContinueResponse
ThreadsRequest
```

Delve installed:
```dlv version
Delve Debugger
Version: 1.0.0-rc.1
Build: $Id: b6077a6a35c48a31716aad2ad3fdf77bbdf70abd $
```

**Comment by ataliadvanstep** [comment]
Hi,

I have exactly the same issue. I am unable to debug from mac os into a docker container.

I use docker-compose :

```
command:
    hostname: command-microservice
    env_file:
      - ./.env
    build:
      context: $GOPATH/src/github.com/imapura/imapura-backend-api-go/
      dockerfile: ./microservice/command/Dockerfile
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    entrypoint: dlv debug ./microservice/command –headless –listen=:2345 –api-version=2 –log
    ports:
      - "2345:2345"
    expose:
      - "2345"
    depends_on:
      - datastore
      - pubsub
    links:
      - datastore
      - pubsub
```

My launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Remote Docker",
            "type": "go",
            "request": "launch",
            "mode": "remote",
            "remotePath": "/go/src/github.com/imapura/imapura-backend-api-go/",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}/",
            "env": {},
            "args": [],
            "trace": true,
            "showLog": true
        }
    ]
}
```

```
Verbose logs are written to:
/var/folders/62/cc5sglt13z78rh_pbdhx_mww0000gn/T/vscode-go-debug.txt
10:58:16 AM, 8/26/2017
InitializeRequest
InitializeResponse
InitializeEvent
SetBreakPointsRequest
All cleared
Creating on: /Users/atali/Development/go/src/github.com/imapura/imapura-backend-api-go/microservice/command/command.go (/go/src/github.com/imapura/imapura-backend-api-go/microservice/command/command.go) :93
Error on CreateBreakpoint
All set:[null]
SetBreakPointsResponse
ConfigurationDoneRequest
ContinueRequest
ContinueResponse
ThreadsRequest
```

If I try to debug manually, the breakpoint match
```
#dlv connect 127.0.0.1:2345
Type 'help' for list of commands.
(dlv) break main.main
Breakpoint 1 set at 0xa16533 for main.main() /go/src/github.com/imapura/imapura-backend-api-go/microservice/command/command.go:89
(dlv) continue
> main.main() /go/src/github.com/imapura/imapura-backend-api-go/microservice/command/command.go:89 (hits goroutine(1):1 total:1) (PC: 0xa16533)
(dlv) next
> main.main() /go/src/github.com/imapura/imapura-backend-api-go/microservice/command/command.go:91 (PC: 0xa16541)
(dlv) next
> main.main() /go/src/github.com/imapura/imapura-backend-api-go/microservice/command/command.go:92 (PC: 0xa165b2)
(dlv)
```

Any advice ?
