### ISSUE TITLE
Inspection of slice element attributes not working correctly in debugger

### ISSUE THREAD

**Issue by michaelkleinhenz** [Microsoft/vscode-go#1804]
Steps to Reproduce:

1. Create a go test which uses `[]interface{}` typed variables:
```
type foo struct {
  FooAttr interface {}
}
var fooVal []foo
fooVal = []foo { foo { FooAttr: "Hello" } }
```
2. Debug and inspect `fooVal`. The debugger shows the correct type of the value, but not the value itself:

(for strings):
```
fooVal:
  [0]:
    FooAttr: <interface {}>
       - data: "" 
```

(for int):
```
fooVal:
  [0]:
    FooAttr: <interface {}>
       - data: <int>
```

For non-slice variables and/or literals, this works.
